import type { Component } from 'vue'
import {
  PlusIcon,
  XMarkIcon,
  CheckIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  HomeIcon,
  ArrowRightStartOnRectangleIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  Cog6ToothIcon,
  MagnifyingGlassIcon,
  FolderIcon,
  ArrowUpTrayIcon,
  DocumentIcon,
  GlobeAltIcon,
  Square2StackIcon,
  Squares2X2Icon,
  CubeIcon,
  AdjustmentsHorizontalIcon,
  BoltIcon,
  RectangleGroupIcon,
  RectangleStackIcon,
  ViewColumnsIcon,
  WindowIcon,
  MapPinIcon,
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  Bars3Icon,
  Bars3BottomLeftIcon,
  DocumentTextIcon,
  ChatBubbleBottomCenterTextIcon,
  ListBulletIcon,
  PaintBrushIcon,
  StopIcon,
  SparklesIcon,
  PencilSquareIcon,
  DocumentDuplicateIcon,
  ClipboardIcon,
  TagIcon,
  TrashIcon,
  LinkIcon,
  VariableIcon,
  PhotoIcon,
  VideoCameraIcon,
  CodeBracketIcon,
  QueueListIcon,
  CursorArrowRaysIcon,
  HashtagIcon,
  CalendarDaysIcon,
  EyeSlashIcon,
  SwatchIcon,
  ComputerDesktopIcon,
  DeviceTabletIcon,
  DevicePhoneMobileIcon,
} from '@heroicons/vue/24/outline'

// Named icons → HeroIcons (24px outline). Rendered by IconUi.
// New glyphs: import the HeroIcon and add a mapping here — never inline <svg>.
export const ICONS: Record<string, Component> = {
  // Common / navigation
  plus: PlusIcon,
  add: PlusIcon,
  close: XMarkIcon,
  check: CheckIcon,
  undo: ArrowUturnLeftIcon,
  redo: ArrowUturnRightIcon,
  home: HomeIcon,
  logout: ArrowRightStartOnRectangleIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-right': ChevronRightIcon,
  settings: Cog6ToothIcon,
  search: MagnifyingGlassIcon,
  folder: FolderIcon,
  upload: ArrowUpTrayIcon,
  document: DocumentIcon,
  globe: GlobeAltIcon,

  // Viewports
  desktop: ComputerDesktopIcon,
  tablet: DeviceTabletIcon,
  mobile: DevicePhoneMobileIcon,

  // Sidebar tabs
  layers: Square2StackIcon,
  elements: Squares2X2Icon,
  components: CubeIcon,
  component: CubeIcon,
  properties: AdjustmentsHorizontalIcon,
  interactions: BoltIcon,

  // Property sections
  layout: RectangleGroupIcon,
  position: MapPinIcon,
  size: ArrowsPointingOutIcon,
  spacing: ArrowsRightLeftIcon,
  typography: Bars3Icon,
  background: PaintBrushIcon,
  border: StopIcon,
  effects: SparklesIcon,

  // Context menu / node actions
  rename: PencilSquareIcon,
  duplicate: DocumentDuplicateIcon,
  copy: DocumentDuplicateIcon,
  paste: ClipboardIcon,
  wrap: ArrowsPointingInIcon,
  unwrap: ArrowsPointingOutIcon,
  'move-up': ArrowUpIcon,
  'move-down': ArrowDownIcon,
  classes: TagIcon,
  delete: TrashIcon,
  'select-parent': ArrowUturnUpIcon,

  // Element & field types
  section: RectangleStackIcon,
  container: RectangleGroupIcon,
  columns: ViewColumnsIcon,
  column: ViewColumnsIcon,
  div: WindowIcon,
  heading: Bars3BottomLeftIcon,
  text: DocumentTextIcon,
  richtext: DocumentTextIcon,
  link: LinkIcon,
  'link-block': LinkIcon,
  span: VariableIcon,
  list: ListBulletIcon,
  blockquote: ChatBubbleBottomCenterTextIcon,
  image: PhotoIcon,
  video: VideoCameraIcon,
  embed: CodeBracketIcon,
  form: QueueListIcon,
  input: Bars3Icon,
  textarea: Bars3BottomLeftIcon,
  select: ChevronDownIcon,
  checkbox: CheckIcon,
  radio: StopIcon,
  label: TagIcon,
  button: CursorArrowRaysIcon,
  collection: ArrowsUpDownIcon,
  number: HashtagIcon,
  date: CalendarDaysIcon,
  'eye-slash': EyeSlashIcon,
  swatch: SwatchIcon,
}

export type IconName = keyof typeof ICONS
