import { h, type Component, type FunctionalComponent } from 'vue'
import {
  PlusIcon,
  XMarkIcon,
  CheckIcon,
  ArrowUturnUpIcon,
  HomeIcon,
  ArrowRightStartOnRectangleIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  Cog6ToothIcon,
  MagnifyingGlassIcon,
  UsersIcon,
  FolderIcon,
  ArrowUpTrayIcon,
  ArrowDownTrayIcon,
  ArchiveBoxIcon,
  DocumentIcon,
  GlobeAltIcon,
  Square2StackIcon,
  Squares2X2Icon,
  CubeIcon,
  AdjustmentsHorizontalIcon,
  BoltIcon,
  RectangleGroupIcon,
  RectangleStackIcon,
  CircleStackIcon,
  WindowIcon,
  MapPinIcon,
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  Bars3Icon,
  Bars3BottomLeftIcon,
  DocumentTextIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  ClockIcon,
  BookmarkIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  EnvelopeIcon,
  ListBulletIcon,
  PaintBrushIcon,
  StopIcon,
  SparklesIcon,
  PencilSquareIcon,
  DocumentDuplicateIcon,
  ClipboardIcon,
  TagIcon,
  TrashIcon,
  LinkIcon,
  VariableIcon,
  PhotoIcon,
  VideoCameraIcon,
  CodeBracketIcon,
  QueueListIcon,
  CursorArrowRaysIcon,
  HashtagIcon,
  CalendarDaysIcon,
  EyeSlashIcon,
  EyeIcon,
  SwatchIcon,
  ComputerDesktopIcon,
  DeviceTabletIcon,
  DevicePhoneMobileIcon,
  ChartBarIcon,
  InboxArrowDownIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  InformationCircleIcon,
  ExclamationTriangleIcon,
  CheckCircleIcon,
  LockClosedIcon,
  MusicalNoteIcon,
  ScaleIcon,
  SunIcon,
  MoonIcon,
} from '@heroicons/vue/24/outline'

// Heroicons has no letterform, so draw a proper "H" for the Heading element.
// `attrs` carries IconUi's size class + aria-hidden through to the <svg>.
const HeadingIcon: FunctionalComponent = (_props, { attrs }) =>
  h(
    'svg',
    { xmlns: 'http://www.w3.org/2000/svg', fill: 'none', viewBox: '0 0 24 24', 'stroke-width': '2', stroke: 'currentColor', ...attrs },
    h('path', { 'stroke-linecap': 'round', 'stroke-linejoin': 'round', d: 'M6 5v14M18 5v14M6 12h12' }),
  )

// Named icons → HeroIcons (24px outline). Rendered by IconUi.
// New glyphs: import the HeroIcon and add a mapping here — never inline <svg>.
export const ICONS: Record<string, Component> = {
  // Common / navigation
  plus: PlusIcon,
  add: PlusIcon,
  close: XMarkIcon,
  check: CheckIcon,
  home: HomeIcon,
  logout: ArrowRightStartOnRectangleIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-right': ChevronRightIcon,
  settings: Cog6ToothIcon,
  search: MagnifyingGlassIcon,
  users: UsersIcon,
  sparkles: SparklesIcon,
  info: InformationCircleIcon,
  alert: ExclamationTriangleIcon,
  'check-circle': CheckCircleIcon,
  lock: LockClosedIcon,
  sun: SunIcon,
  moon: MoonIcon,
  folder: FolderIcon,
  upload: ArrowUpTrayIcon,
  download: ArrowDownTrayIcon,
  archive: ArchiveBoxIcon,
  document: DocumentIcon,
  globe: GlobeAltIcon,
  'arrow-right': ArrowRightIcon,
  'external-link': ArrowTopRightOnSquareIcon,

  // Dashboard
  analytics: ChartBarIcon,
  submissions: InboxArrowDownIcon,
  'trend-up': ArrowTrendingUpIcon,
  'trend-down': ArrowTrendingDownIcon,
  eye: EyeIcon,
  preview: EyeIcon,

  // Viewports
  desktop: ComputerDesktopIcon,
  tablet: DeviceTabletIcon,
  mobile: DevicePhoneMobileIcon,

  // Sidebar tabs
  layers: Square2StackIcon,
  elements: Squares2X2Icon,
  components: CubeIcon,
  component: CubeIcon,
  properties: AdjustmentsHorizontalIcon,
  interactions: BoltIcon,

  // Property sections
  layout: RectangleGroupIcon,
  position: MapPinIcon,
  size: ArrowsPointingOutIcon,
  spacing: ArrowsRightLeftIcon,
  typography: Bars3Icon,
  background: PaintBrushIcon,
  border: StopIcon,
  effects: SparklesIcon,

  // Context menu / node actions
  rename: PencilSquareIcon,
  duplicate: DocumentDuplicateIcon,
  copy: DocumentDuplicateIcon,
  paste: ClipboardIcon,
  wrap: ArrowsPointingInIcon,
  unwrap: ArrowsPointingOutIcon,
  'move-up': ArrowUpIcon,
  'move-down': ArrowDownIcon,
  classes: TagIcon,
  delete: TrashIcon,
  'select-parent': ArrowUturnUpIcon,

  // Element & field types
  section: RectangleStackIcon,
  container: RectangleGroupIcon,
  div: WindowIcon,
  heading: HeadingIcon,
  text: Bars3BottomLeftIcon,
  richtext: DocumentTextIcon,
  markdown: DocumentTextIcon,
  link: LinkIcon,
  span: VariableIcon,
  list: ListBulletIcon,
  blockquote: ChatBubbleBottomCenterTextIcon,
  comment: ChatBubbleOvalLeftEllipsisIcon,
  history: ClockIcon,
  pin: BookmarkIcon,
  undo: ArrowUturnLeftIcon,
  redo: ArrowUturnRightIcon,
  mail: EnvelopeIcon,
  image: PhotoIcon,
  video: VideoCameraIcon,
  audio: MusicalNoteIcon,
  weight: ScaleIcon,
  embed: CodeBracketIcon,
  form: QueueListIcon,
  input: Bars3Icon,
  textarea: Bars3BottomLeftIcon,
  select: ChevronDownIcon,
  checkbox: CheckIcon,
  radio: StopIcon,
  label: TagIcon,
  button: CursorArrowRaysIcon,
  collection: ArrowsUpDownIcon,
  'collection-list': CircleStackIcon,
  'collection-item': Square2StackIcon,
  number: HashtagIcon,
  date: CalendarDaysIcon,
  'eye-slash': EyeSlashIcon,
  swatch: SwatchIcon,
}

export type IconName = keyof typeof ICONS
